import json
import sys
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np

# WSIMOD imports
from wsimod.core import constants
from wsimod.arcs.arcs import Arc
from wsimod.nodes.catchment import Catchment
from wsimod.nodes.demand import ResidentialDemand
from wsimod.nodes.land import Land
from wsimod.nodes.nodes import Node
from wsimod.nodes.sewer import Sewer
from wsimod.nodes.storage import Groundwater, Reservoir
from wsimod.nodes.waste import Waste
from wsimod.nodes.wtw import FWTW, WWTW
from wsimod.orchestration.model import Model

constants.POLLUTANTS = ["temperature", "nitrate"]
constants.NON_ADDITIVE_POLLUTANTS = ["temperature"]
constants.ADDITIVE_POLLUTANTS = ["nitrate"]
constants.FLOAT_ACCURACY = 1e-9
constants.POLLUTANTS

"""
WSIMOD Water Cycle Simulation Script
Adapted for local use with Godot.
- Reads a JSON file generated by Godot (fixed absolute path).
- Constructs nodes and arcs, adding missing automatic connections.
- Runs the WSIMOD model (version 0.8.1).
"""

def load_input_data(input_data_path):
    assert input_data_path != None, "Specify a path for the input_data"
    input_data = pd.read_csv(input_data_path)

    input_data = input_data.loc[input_data.variable.isin(["flow", "precipitation", "et0", "temperature", "nitrate"])]
    input_data.loc[input_data.variable == "flow", "value"] *= constants.M3_S_TO_M3_DT
    input_data.loc[input_data.variable == "precipitation", "value"] *= constants.MM_TO_M
    input_data.loc[input_data.variable == "et0", "value"] *= constants.MM_TO_M
    input_data.loc[input_data.variable == "nitrate", "value"] *= constants.MG_L_TO_KG_M3

    input_data.date = pd.to_datetime(input_data.date)
    data_input_dict = input_data.set_index(["variable", "date"]).value.to_dict()
    data_input_dict = (
        input_data.groupby("site")
        .apply(lambda x: x.set_index(["variable", "date"]).value.to_dict())
        .to_dict()
    )
    #print(pd.concat([input_data.head(5), input_data.sample(10), input_data.tail(5)]))

    # Keep dates such that we have a value for each variable
    dates = input_data.loc[input_data.variable == "flow", "date"]
    for variable in ["precipitation", "et0", "nitrate", "temperature"]:# get common measure times across all stations
        dates = pd.merge(dates, input_data.loc[input_data.variable == variable, "date"], how='inner', on=['date']).date
    dates = dates.unique()
    dates = dates[dates.argsort()]

    return data_input_dict, dates

def main():
    if len(sys.argv) < 3:
        print("Error: Provide JSON file and output image path")
        sys.exit(1)
    
    json_file = sys.argv[1]
    output_dir = sys.argv[2]

    try:
        os.makedirs(output_dir, exist_ok=True)
    except OSError as e:
        print(f"Error creating output directory: {e}")
    
    try:
        # ---------------------------------------------------------------------------
        # Load JSON data
        # ---------------------------------------------------------------------------
        with open(json_file, 'r', encoding='utf-8-sig') as f:
            data = json.load(f)

        nodes_data = data.get("nodes", {})
        arcs_data = data.get("arcs", {})
        print(f"Loaded {len(nodes_data)} nodes and {len(arcs_data)} explicit arcs from JSON")


        model_dates = None

        # ---------------------------------------------------------------------------
        # Build WSIMOD node objects
        # ---------------------------------------------------------------------------
        nodes = {}

        # Land node
        land_data_input_dict, dates = load_input_data(data["input_data_paths"][data["nodes"]["land"]["attributes"]["input_data"]])
        land_inputs = land_data_input_dict["land"]
        
        model_dates = dates

        pollutant_deposition = {
            "nitrate": 2e-9
        }

        nodes["land"] = Land(
            name="land",
            surfaces=[
                {
                    "type_": "PerviousSurface",
                    "pollutant_load": pollutant_deposition,
                    "surface": "rural",
                    **nodes_data["land"]["attributes"]["pervious"]
                },
                {
                    "type_": "ImperviousSurface",
                    "pollutant_load": pollutant_deposition,
                    "surface": "urban",
                    **nodes_data["land"]["attributes"]["impervious"]
                },
            ],
            data_input_dict=land_inputs
        )

        # Sewer node
        nodes["sewer"] = Sewer(
            name="sewer",
            **nodes_data["sewer"]["attributes"]
        )

        nodes["gw"] = Groundwater(name="gw", capacity=3.2e9, area=3.2e8, residence_time=20)

        # Other nodes
        for name, ndata in nodes_data.items():
            attrs = ndata.get("attributes", {}) or {}
            if name.startswith("catchment_"):
                data_input_dict, dates = load_input_data(data["input_data_paths"][ndata["attributes"]["input_data"]])
                nodes[name] = Catchment(
                    name=name, 
                    data_input_dict=data_input_dict["river"]
                )
                model_dates = list(set(model_dates) & set(dates))
                print("len model dates", len(model_dates))
            if name.startswith("river_"):
                nodes[name] = Node(name=name)
            if name.startswith("residential_"):
                nodes[name] = ResidentialDemand(
                    name=name,
                    **ndata["attributes"],
                    pollutant_load={
                        "temperature": 14,
                        "nitrate": 60 * constants.MG_L_TO_KG_M3 * 0.12 # 60 mg/L
                    },
                    data_input_dict=land_inputs
                )
            if name.startswith("fwtw_"):
                nodes[name] = FWTW(
                    name=name,
                    **ndata["attributes"]
                )
            if name.startswith("wwtw_"):
                nodes[name] = WWTW(
                    name=name,
                    **ndata["attributes"]
                )
            if name.startswith("outlet_"):
                nodes[name] = Waste(name=name)
            
        # ---------------------------------------------------------------------------
        # Build explicit arcs from JSON
        # ---------------------------------------------------------------------------

        arcs = []
        arcs_from = {}
        arcs_to = {}
        for arc_name, arc_info in arcs_data.items():
            src = arc_info.get("from")
            dst = arc_info.get("to")
            arcs_from[src] = arcs_from.get(src, []) + [arc_name]
            arcs_to[dst] = arcs_to.get(dst, []) + [arc_name]
            arc_type = src.split("_")[0] + "_to_" + dst.split("_")[0]
            match arc_type:
                case "residential_to_wwtw":
                    arcs.append(Arc(name=f"{src}_to_sewer", in_port=nodes[src], out_port=nodes["sewer"]))
                case _:
                    arcs.append(Arc(name=arc_name, in_port=nodes[src], out_port=nodes[dst]))
        
        arcs.append(Arc(in_port=nodes["land"], out_port=nodes["sewer"], name="land_to_sewer"))
        arcs.append(Arc(in_port=nodes["land"], out_port=nodes["gw"], name="land_to_gw"))

        for node in nodes:
            if node.startswith("fwtw_"):
                arcs.append(Arc(name=f"{node}_to_sewer", in_port=nodes[node], out_port=nodes["sewer"]))
            if node.startswith("wwtw_"):
                arcs.append(Arc(name=f"sewer_to_{node}", in_port=nodes["sewer"], out_port=nodes[node], preference=1e10))
                downstream_river = None
                for arc in arcs_from[node]:
                    if arcs_data[arc]["to"].split("_")[0] == "river":
                        downstream_river = nodes[arcs_data[arc]["to"]]
                    break
                arcs.append(Arc(name=f"sewer_overflow_{node.split("_")[1]}", in_port=nodes["sewer"], out_port=downstream_river, preference=1e-10))
            if node.startswith("outlet_"):
                arcs.append(Arc(name=f"gw_to_{node}", in_port=nodes["gw"], out_port=nodes[node]))
        
        # ---------------------------------------------------------------------------
        # Initialise and run the WSIMOD model
        # ---------------------------------------------------------------------------

        model_dates = np.array(model_dates)
        model_dates = model_dates[model_dates.argsort()]

        model = Model()
        model.add_instantiated_nodes(list(nodes.values()))
        model.add_instantiated_arcs(arcs)
        model.dates = model_dates

        model.save(output_dir)

        flows, tanks, _, surfaces = model.run()

        print("Model ran successfully")

        # ---------------------------------------------------------------------------
        # Generate plot
        # ---------------------------------------------------------------------------

        flows = pd.DataFrame(flows)
        flows_plot = flows.copy()
        flows_plot["nitrate"] /= flows_plot.flow

        unique_arcs = flows['arc'].unique()
        unique_arcs = np.array([arc for arc in unique_arcs if not arc.startswith("river_")])
        
        num_arcs = len(unique_arcs)
        cols = 3
        rows = (num_arcs + cols - 1) // cols

        fig, axes = plt.subplots(rows, cols, figsize=(15, 4 * rows), constrained_layout=True)
        axes = axes.flatten()

        for i, arc_name in enumerate(unique_arcs):
            ax = axes[i]
            # filter data for this arc and set time as index for plotting
            arc_data = flows[flows['time'] > pd.to_datetime('2022-07-01')].loc[flows['arc'] == arc_name, ["flow", "time"]].set_index("time")
            ax.plot(arc_data.index, arc_data['flow'])
            ax.set_title(arc_name)
            ax.set_ylabel("Flow (m3/d)")
            ax.grid(True, linestyle='--', alpha=0.7)
            # Rotate date labels for better readability
            ax.tick_params(axis='x', rotation=45)

        # Turn off unused subplots
        for i in range(num_arcs, len(axes)):
            axes[i].axis('off')

        plt.show()
        
    except FileNotFoundError:
        print(f"Error: File '{json_file}' not found")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()

