"""
WSIMOD Water Cycle Simulation Script
Adapted for local use with Godot.
- Reads a JSON file generated by Godot (fixed absolute path).
- Constructs nodes and arcs, adding missing automatic connections.
- Runs the WSIMOD model (version 0.8.1).
- Saves results to json and creates a matplotlib plots.
"""

import json
import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

# WSIMOD imports (version 0.8.1)
from wsimod.nodes.nodes import Node
from wsimod.nodes.storage import River
from wsimod.nodes.catchment import Catchment
from wsimod.nodes.land import Land
from wsimod.nodes.sewer import Sewer as Foul
from wsimod.nodes.wtw import WWTW
from wsimod.arcs.arcs import Arc
from wsimod.orchestration.model import Model

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
# Absolute path to the JSON file produced by Godot
JSON_PATH = Path(r"C:\Users\USER\Downloads\Nouveau dossier\data.json")
# Output paths
CSV_OUTPUT = Path(r"C:\Users\USER\Downloads\Nouveau dossier\results.csv")
PLOT_OUTPUT = Path(r"C:\Users\USER\Downloads\Nouveau dossier\results.png")

if not JSON_PATH.is_file():
    raise FileNotFoundError(f"JSON file not found at {JSON_PATH}")

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
def safe_create(cls, name, **kwargs):
    """Create a WSIMOD node, swallowing unexpected kwargs.
    Some WSIMOD classes have changed signatures between releases.
    """
    try:
        return cls(name=name, **kwargs)
    except TypeError:
        return cls(name=name)

# ---------------------------------------------------------------------------
# Load JSON data
# ---------------------------------------------------------------------------
with open(JSON_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

nodes_data = data.get("nodes", {})
arcs_data = data.get("arcs", {})
print(f"Loaded {len(nodes_data)} nodes and {len(arcs_data)} explicit arcs from JSON")

# ---------------------------------------------------------------------------
# Build WSIMOD node objects
# ---------------------------------------------------------------------------
nodes = {}
for name, ndata in nodes_data.items():
    attrs = ndata.get("attributes", {}) or {}
    if name.startswith("river_"):
        nodes[name] = safe_create(River, name,
                                 length=attrs.get("length", 1000),
                                 width=attrs.get("width", 10))
    elif name.startswith("catchment"):
        nodes[name] = safe_create(Catchment, name, area=attrs.get("area", 100e6))
    elif name.startswith("ruralLand"):
        nodes[name] = safe_create(Land, name,
                                 area=attrs.get("area", 1e5),
                                 depth=0.5,
                                 field_capacity=0.3)
    elif name.startswith("urbanLand"):
        nodes[name] = safe_create(Land, name,
                                 area=attrs.get("area", 1e5),
                                 depth=0.3,
                                 field_capacity=0.2)
    elif name.startswith("residential"):
        nodes[name] = safe_create(Foul, name,
                                 population=attrs.get("population", 10000),
                                 per_capita=attrs.get("per_capita", 0.15))
    elif name.startswith("wwtw"):
        nodes[name] = safe_create(WWTW, name,
                                 treatment_throughput_capacity=attrs.get("treatment_throughput_capacity", 5000))
    elif name.startswith("outlet"):
        nodes[name] = safe_create(Node, name)
    else:
        nodes[name] = safe_create(Node, name)

print(f"Created {len(nodes)} WSIMOD node instances")

# ---------------------------------------------------------------------------
# Build explicit arcs from JSON
# ---------------------------------------------------------------------------
arcs = []
for arc_name, arc_info in arcs_data.items():
    src = arc_info.get("from")
    dst = arc_info.get("to")
    if src in nodes and dst in nodes:
        arcs.append(Arc(name=arc_name, in_port=nodes[src], out_port=nodes[dst]))

# ---------------------------------------------------------------------------
# Automatic connections (as described in the specification)
# ---------------------------------------------------------------------------
# 1. Rivers in series based on naming convention "river_x_y_z"
river_prefixes = set()
for name in nodes:
    if name.startswith("river_"):
        parts = name.split("_")
        if len(parts) >= 4:
            prefix = "_".join(parts[:3]) + "_"
            river_prefixes.add(prefix)

for prefix in river_prefixes:
    seq = sorted([n for n in nodes if n.startswith(prefix)],
                 key=lambda x: int(x.split("_")[-1]))
    for i in range(len(seq) - 1):
        arcs.append(Arc(name=f"{seq[i]}_to_{seq[i+1]}",
                        in_port=nodes[seq[i]], out_port=nodes[seq[i+1]]))

# 2. Catchment connects to first river of each branch
catchment_node = next((n for n in nodes if n.startswith("catchment")), None)
if catchment_node:
    for prefix in river_prefixes:
        first = min([n for n in nodes if n.startswith(prefix)],
                    key=lambda x: int(x.split("_")[-1]))
        if not any(a.in_port == nodes[catchment_node] and a.out_port == nodes[first] for a in arcs):
            arcs.append(Arc(name=f"{catchment_node}_to_{first}",
                            in_port=nodes[catchment_node], out_port=nodes[first]))

# 3. Land nodes connect to a downstream river (choose first branch's first river)
land_nodes = [n for n in nodes if n.startswith("ruralLand") or n.startswith("urbanLand")]
if land_nodes and river_prefixes:
    # Choose the first river of the first prefix as a representative downstream point
    first_prefix = sorted(river_prefixes)[0]
    downstream = min([n for n in nodes if n.startswith(first_prefix)],
                    key=lambda x: int(x.split("_")[-1]))
    for land in land_nodes:
        arcs.append(Arc(name=f"{land}_to_{downstream}",
                        in_port=nodes[land], out_port=nodes[downstream]))

# 4. Wastewater treatment (WWTW) connects to a nearby river (fallback to any river)
wwtw_node = next((n for n in nodes if n.startswith("wwtw")), None)
if wwtw_node:
    candidate = next((n for n in nodes if n.startswith("river_")), None)
    if candidate:
        arcs.append(Arc(name=f"{wwtw_node}_to_{candidate}",
                        in_port=nodes[wwtw_node], out_port=nodes[candidate]))

# 5. Outlets connect to the last river of each branch
outlets = sorted([n for n in nodes if n.startswith("outlet")])
for i, prefix in enumerate(sorted(river_prefixes)):
    seq = sorted([n for n in nodes if n.startswith(prefix)],
                 key=lambda x: int(x.split("_")[-1]))
    if seq and i < len(outlets):
        arcs.append(Arc(name=f"{seq[-1]}_to_{outlets[i]}",
                        in_port=nodes[seq[-1]], out_port=nodes[outlets[i]]))

print(f"Total arcs after automatic connections: {len(arcs)}")

# ---------------------------------------------------------------------------
# Initialise and run the WSIMOD model
# ---------------------------------------------------------------------------
model = Model()
# WSIMOD 0.8.1 has a known bug with add_instantiated_arcs; the workaround is to
# first add nodes, then manually ensure the internal node-type dict contains the
# 'Waste' entry before adding arcs.
model.add_instantiated_nodes(list(nodes.values()))
# Ensure the 'Waste' entry exists to avoid a KeyError inside the library.
model.nodes_type["Waste"] = model.nodes_type.get("Waste", {})
model.add_instantiated_arcs(arcs)

# Constant rainfall input (example: 5 mm/day over the whole catchment area)
# Adjust as needed for your game scenario.
start_date = pd.Timestamp("2024-01-01")
end_date = pd.Timestamp("2024-01-03")
dates = pd.date_range(start_date, end_date, freq="D")
# Convert 5 mm/day to m³/s assuming 100 km² catchment (adjust if you have real area)
rainfall_rate = 0.005 / 86400 * 100e6  # m³/s
rainfall_series = pd.Series(rainfall_rate, index=dates)
model.data_input["rainfall"] = rainfall_series

print("Running simulation...")
model.run(dates=dates)
print("Simulation completed")

# ---------------------------------------------------------------------------
# Extract results and save to CSV
# ---------------------------------------------------------------------------
results = {}
for name, node in nodes.items():
    if hasattr(node, "storage") and node.storage is not None:
        results[name] = node.storage

if not results:
    raise RuntimeError("No storage results were produced by the simulation.")

df = pd.DataFrame(results, index=dates)
CSV_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(CSV_OUTPUT)
print(f"Results saved to {CSV_OUTPUT}")

# ---------------------------------------------------------------------------
# Visualisation with Matplotlib
# ---------------------------------------------------------------------------
plt.figure(figsize=(12, 6))
for col in df.columns:
    plt.plot(df.index, df[col], label=col)
plt.title("Water storage over time per node")
plt.xlabel("Date")
plt.ylabel("Storage (m³)")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
PLOT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
plt.savefig(PLOT_OUTPUT)
print(f"Plot saved to {PLOT_OUTPUT}")

# Optionally, display the plot when running locally (non‑headless environments)
# plt.show()

# End of script